mqtt:
  host: mqtt.hisatochii.id.vn
  port: 8883
  tls: true
simulation:
  tenant_id: default
  speed: 10
  initial_pumps: 100
  min_pumps: 100
  max_pumps: 500
  step_size: 100
  scale_interval: 1800
pool:
  size: 5
